src/blog/urls.py
from django.urls import path
from . import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('', blog_views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>/', blog_views.PostDetailView.as_view(), name='post'),
    path('created_by/<int:author_pk>/', blog_views.CreatedByListView.as_view(), name='created_by'),
    path('category/<slug:slug>/', blog_views.CategoryListView.as_view(), name='category'),
    path('tag/<slug:slug>/', blog_views.TagListView.as_view(), name='tag'),
    path('search/', blog_views.SearchListView.as_view(), name='search'),
]

src/main/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('minecraft-data/', views.minecraft_data, name='minecraft_data'),
    path('guide/<str:page>/', views.server_guide_replace, name='guide_replacement'),
    path('guide/', views.server_guide, name='guide'),
    # Other paths...
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from subscriptions import views as subscriptions_views
from checkouts import views as checkout_views
from main import views as main_views
from django.conf.urls import handler404

handler404 = 'main.views.custom_404_view'

urlpatterns = [
    path('', main_views.home, name='home'),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('docs/', include('documents.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('staff/', admin.site.urls, name='staff'),
    

    path('accounts/billing/', subscriptions_views.user_subscription_view, name='user_subscription'),
    path('accounts/billing/cancel', subscriptions_views.user_subscription_cancel_view, name='user_subscription_cancel'),

    path("pricing/", subscriptions_views.subscription_price_view, name='pricing'),
    path("pricing/<str:interval>/", subscriptions_views.subscription_price_view, name='pricing_interval'),

    path("checkout/sub-price/<int:price_id>/", 
            checkout_views.product_price_redirect_view,
            name='sub-price-checkout'
            ),
    path("checkout/start/", 
            checkout_views.checkout_redirect_view,
            name='stripe-checkout-start'
            ),
    path("checkout/success/", 
            checkout_views.checkout_finalize_view,
            name='stripe-checkout-end'
            ),

        # Minecraft
        path("vip/subscribe/", subscriptions_views.post_subscription_minecraft_user, name='vip-subscribe'),

        
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

src/templates/partials/footer.html
{% load static %}

<footer class="footer section-wrapper">
  <div class="section-content-wide">
    <div class="footer-gap">
      <div class="center">
        Copyright © {% now "Y" %} <a href="{% url 'home' %}">{{ APP_NAME }}</a>
      </div>
      <div class="center">
      <small>
        {% for doc in documents %}
          <a href="{{ doc.get_absolute_url }}" class="link">{{ doc.name }}</a>
          {% if not forloop.last %} | {% endif %}
        {% endfor %}
      </small>
      {% if user.is_authenticated and user.is_staff %}
    <br><br><a href="{% url 'admin:index' %}">Access Dashboard (Staff Only)</a><br><br>
    {% endif %}
    </div>
            
  </div>
</footer>

src/templates/partials/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page_title }}{{ APP_NAME }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/remedy.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'olipvp-icon.png' %}" type="image/png">
    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
</head>

src/templates/partials/header.html
{% load static %}

<header class="header">
  <div class="section-content-wide">
    <nav class="menu">
      <li id="website-title" class="menu-item">
        <a href="{% url 'home' %}">
          OliPvP
        </a>
      </li>
      </li>
      <ul class="menu-items">
        <li class="menu-item">
          <a href="{% url 'main:guide' %}">
            <img class="menu-icon" src="{% static 'icons/guide.png' %}" alt="Ranks">Guide</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'blog:home' %}">
            <img class="menu-icon" src="{% static 'icons/love.png' %}" alt="News">News</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'pricing' %}">
            <img class="menu-icon" src="{% static 'icons/plan3.png' %}" alt="Prices">Memberships
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="menu-item">
          <a href="{% url 'user_subscription' %}">
            <img class="menu-icon" src="{% static 'icons/man.png' %}" alt="Logout">You</a>
        </li>
        {% else %}
        <li class="menu-item">
          <a class="menu-link" href="{% url 'account_login' %}">
            <img class="menu-icon" src="{% static 'icons/man.png' %}" alt="Login">Login</a>
        </li>
        {% endif %}
        <li class="menu-item" id="theme-toggle">
          <a style="cursor: pointer;">
            <img id="theme-icon" class="menu-icon" src="{% static 'icons/moon.png' %}" alt="Night Theme">
          </a>
        </li>
      </ul>
    </nav>
  </div>
</header>

src/templates/partials/messages.html
{% if messages %}
    <div>
        {% for message in messages %}
            <div class="message"
                    role="alert">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    </div>
{% endif %}

src/templates/partials/nothing.html
<article class="card nothing-found">
  <div class="card-text-wrapper">
    {% if extra %}
    <h1>{{ extra }}<span class="card-icon">😔</span></h1>
    {% else %}
    <h1>Nothing found!<span class="card-icon">😔</span></h1>
    {% endif %}

    <div class="mb-base"></div>
    <p>
      We couldn't find what you were looking for. Go back to the <a href="{% url 'home' %}">home page</a>.
    </p>
  </div>
</article>

src/templates/partials/scripts.html
{% load static %}

<script src="{% static 'js/codemirror.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<script src="{% static 'js/copy.js' %}"></script>