src/blog/urls.py
from django.urls import path
from . import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('', blog_views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>/', blog_views.PostDetailView.as_view(), name='post'),
    path('created_by/<int:author_pk>/', blog_views.CreatedByListView.as_view(), name='created_by'),
    path('category/<slug:slug>/', blog_views.CategoryListView.as_view(), name='category'),
    path('tag/<slug:slug>/', blog_views.TagListView.as_view(), name='tag'),
    path('search/', blog_views.SearchListView.as_view(), name='search'),
]

src/main/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('minecraft-data/', views.minecraft_data, name='minecraft_data'),
    path('guide/<str:page>/', views.server_guide_replace, name='guide_replacement'),
    path('guide/', views.server_guide, name='guide'),
    # Other paths...
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from subscriptions import views as subscriptions_views
from checkouts import views as checkout_views
from main import views as main_views
from django.conf.urls import handler404

handler404 = 'main.views.custom_404_view'

urlpatterns = [
    path('', main_views.home, name='home'),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('docs/', include('documents.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('staff/', admin.site.urls, name='staff'),
    

    path('accounts/billing/', subscriptions_views.user_subscription_view, name='user_subscription'),
    path('accounts/billing/cancel', subscriptions_views.user_subscription_cancel_view, name='user_subscription_cancel'),

    path("pricing/", subscriptions_views.subscription_price_view, name='pricing'),
    path("pricing/<str:interval>/", subscriptions_views.subscription_price_view, name='pricing_interval'),

    path("checkout/sub-price/<int:price_id>/", 
            checkout_views.product_price_redirect_view,
            name='sub-price-checkout'
            ),
    path("checkout/start/", 
            checkout_views.checkout_redirect_view,
            name='stripe-checkout-start'
            ),
    path("checkout/success/", 
            checkout_views.checkout_finalize_view,
            name='stripe-checkout-end'
            ),

        # Minecraft
        path("vip/subscribe/", subscriptions_views.post_subscription_minecraft_user, name='vip-subscribe'),

        
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

src/main/models.py
from django.db import models

# Costumer model

import helpers.billing
from django.conf import settings
from django.db import models

from allauth.account.signals import (
    user_signed_up as allauth_user_signed_up,
    email_confirmed as allauth_email_confirmed
)

User = settings.AUTH_USER_MODEL # "auth.user"


class Rank(models.Model):
    name = models.CharField(max_length=120)
    money = models.IntegerField(help_text="Cost to reach rank", blank=True, null=True)
    color = models.CharField(max_length=120, help_text="Color for rank", blank=True, null=True)
    level = models.IntegerField(unique=True, help_text="Level of rank")
    image = models.ImageField(upload_to='ranks/', null=True, blank=True)
    features = models.TextField(help_text="Features for rank, seperated by new line", blank=True, null=True)
    active = models.BooleanField(default=False, help_text="Is this rank active?")

    @property
    def display_features_list(self):
        return [x.strip() for x in self.features.split("\n")]

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_id = models.CharField(max_length=120, null=True, blank=True)
    init_email = models.EmailField(blank=True, null=True)
    init_email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"

    def save(self, *args, **kwargs):
        if not self.stripe_id:
            if self.init_email_confirmed and self.init_email:
                email = self.init_email
                if email != "" and email is not None:
                    stripe_id = helpers.billing.create_customer(email=email,metadata={
                        "user_id": self.user.id, 
                        "username": self.user.username
                    }, raw=False)
                    self.stripe_id = stripe_id
        super().save(*args, **kwargs)
        # post -svae will not update
        # self.stripe_id = "something else"
        # self.save()


def allauth_user_signed_up_handler(request, user, *args, **kwargs):
    email = user.email
    Customer.objects.create(
        user=user,
        init_email=email,
        init_email_confirmed=False,
    )

allauth_user_signed_up.connect(allauth_user_signed_up_handler)


def allauth_email_confirmed_handler(request, email_address, *args, **kwargs):
    qs = Customer.objects.filter(
        init_email=email_address,
        init_email_confirmed=False,
    )
    # does not send the save method or create the
    # stripe customer
    # qs.update(init_email_confirmed=True)
    for obj in qs:
        obj.init_email_confirmed=True
        # send the signal
        obj.save()


allauth_email_confirmed.connect(allauth_email_confirmed_handler)

src/main/views.py
from django.shortcuts import render
from django.conf import settings
from helpers.minecraft import server_info
from .models import Rank
from documents.models import Document, DocumentType


def home(request):

    return render(
        request=request,
        template_name="main/home.html",
        context= {
            'page_title': "",
        })

def minecraft_data(request):
    data = server_info()
    return render(
        request=request,
        template_name="main/partials/minecraft_data.html",
        context= {
            'data': data,
        })

def server_guide(request):
    guide = Document.objects \
        .filter(classification=DocumentType.GUIDE) \
        .filter(active=True).filter(slug='guide') \
        .first()

    return render(
        request=request,
        template_name="main/guide.html",
        context= {
            'guide': guide,
            'page_title': "Guide - ",
        })

def server_guide_replace(request, page):
    if(page == "ranks"):
        ranks = Rank.objects.filter(active=True).order_by('level')
        return render(
            request=request,
            template_name="main/partials/ranks.html",
            context= {
                'ranks': ranks,
            })
    else:
        guide = Document.objects \
            .filter(classification=DocumentType.GUIDE) \
            .filter(active=True).filter(slug='guide') \
            .first()
        return render(
            request=request,
            template_name="main/partials/guide_manual.html",
            context= { 'guide': guide,})

def custom_404_view(request, exception):
        return render(request, '404_template.html', status=404)

    

src/main/templates/main/guide.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<main class="main-content main-background section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">
      <div class="options">
        <a hx-get="{% url 'main:guide_replacement' page=' ' %}" hx-target="#manual-container" hx-swap="outerHTML">
          Guide
        </a>
        <a hx-get="{% url 'main:guide_replacement' page='ranks' %}" hx-target="#manual-container" hx-swap="outerHTML">
          Ranks
        </a>
      </div>
      {% include "main/partials/guide_manual.html" with guide=guide %}
    </div>
  </div>
</main>

{% endblock content %}

src/main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<main class="main-content main-background section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">
      <h1>Welcome {% if user.is_authenticated %} {{ user.first_name }} {{ user.last_name }} {% endif %} to {{ APP_NAME }}</h1>
      <p>
        This a server that works on a ranking system. New privileges and features are unlocked as you rank up. 
        Join us, play with friends, participate in events. Find server information and purchase memberships to enhance your experience. 
        Join us and start your adventure today!  
      </p>

      <h2>Server</h2>
      <div class="separator-main"></div>
      <div class="server-data" id="minecraft-data-container" hx-get="{% url 'main:minecraft_data' %}" hx-trigger="load delay:2s" hx-swap="innerHTML">
        <p class="">Loading servers data...</p>
      </div>
    </div>   
  </div>
</main>
{% endblock content %}

src/main/templates/main/success.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<h1>Success welcome!</h1>

{{ subscription }}
{{ checkout }}


{% endblock content %}

src/main/templates/main/user_cancel_view.html
{% extends 'base.html' %}
{% block content %}

<div class="section-wrapper center-vertical">
    <div class="section-content-wide">
        <div class="section-gap">

            {% if subscription.is_active_status %}

            <h1>Are you sure you want to cancel {{ subscription.plan_name }}?</h1>

            {% csrf_token %}
            <form action="" method="POST">
                <button class="btn mb-base" type="submit">Yes, cancel</button>
            </form>
            <a href="{{ subscription.get_absolute_url}}">No, go back</a>

            {% else %}

            <h1>Your membership is not longer active</h1>

            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}

src/main/templates/main/user_detail_view.html
{% extends 'base.html' %}

{% block content %}

<div class="main-content section-wrapper center-vertical">
    <div class="section-content-wide">
        <div class="section-gap">
            <h1>Your Account Information</h1>
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Name: {{ user.first_name }} {{ user.last_name }}</p><br>
            <p>Plan name: {{ subscription.plan_name }}</p>
            <p>Status: {{ subscription.status|title }}</p>
            <p>Membership age: {{ subscription.original_period_start|timesince }} </p>
            <p>Start: {{ subscription.current_period_start }}</p>
            <p class="mb-base">End: {{ subscription.current_period_end|timeuntil }} ({{ subscription.current_period_end }})</p>
            <a href="{% url 'vip-subscribe' %}">Refresh my subscription on the servers</a><br><br>
            <a href="{% url 'account_logout' %}">Logout from Account</a><br><br>
            <a href="{{ subscription.get_cancel_url }}">Cancel Membership</a>
        </div>
    </div>
</div>

{% endblock content %}