src/blog/urls.py
from django.urls import path
from . import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('', blog_views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>/', blog_views.PostDetailView.as_view(), name='post'),
    path('created_by/<int:author_pk>/', blog_views.CreatedByListView.as_view(), name='created_by'),
    path('category/<slug:slug>/', blog_views.CategoryListView.as_view(), name='category'),
    path('tag/<slug:slug>/', blog_views.TagListView.as_view(), name='tag'),
    path('search/', blog_views.SearchListView.as_view(), name='search'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from subscriptions import views as subscriptions_views
from checkouts import views as checkout_views
from main import views as main_views
from django.conf.urls import handler404

handler404 = 'main.views.custom_404_view'

urlpatterns = [
    path('', main_views.home, name='home'),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('docs/', include('documents.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('staff/', admin.site.urls, name='staff'),
    

    path('accounts/billing/', subscriptions_views.user_subscription_view, name='user_subscription'),
    path('accounts/billing/cancel', subscriptions_views.user_subscription_cancel_view, name='user_subscription_cancel'),

    path("pricing/", subscriptions_views.subscription_price_view, name='pricing'),
    path("pricing/<str:interval>/", subscriptions_views.subscription_price_view, name='pricing_interval'),

    path("checkout/sub-price/<int:price_id>/", 
            checkout_views.product_price_redirect_view,
            name='sub-price-checkout'
            ),
    path("checkout/start/", 
            checkout_views.checkout_redirect_view,
            name='stripe-checkout-start'
            ),
    path("checkout/success/", 
            checkout_views.checkout_finalize_view,
            name='stripe-checkout-end'
            ),

        # Minecraft
        path("vip/subscribe/", subscriptions_views.post_subscription_minecraft_user, name='vip-subscribe'),

        
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

src/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from helpers.rands import slugify_new
from helpers.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse

# Create your models here.
class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

class PostManager(models.Manager):
    def get_published(self):
        return self\
            .filter(is_published=True)\
            .order_by('-pk')


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    objects = PostManager()

    title = models.CharField(max_length=65,)
    slug = models.SlugField(
        unique=True,
        default="",
        null=False,
        blank=True,
        max_length=255
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text=(
            'Este campo precisará estar marcado '
            'para o post ser exibido publicamente.'
        ),
    )
    content = models.TextField()
    cover = models.ImageField(upload_to='posts/%Y/%m/', blank=True, default='')
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text='Se marcado, exibirá a capa dentro do post.',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    # user.post_created_by.all
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='post_created_by'
    )
    updated_at = models.DateTimeField(auto_now=True)
    # user.post_updated_by.all
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='post_updated_by'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
    )
    tags = models.ManyToManyField(Tag, blank=True, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            resize_image(self.cover, 900, True, 70)

        return super_save


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            resize_image(self.file, 900, True, 70)

        return super_save

src/blog/views.py
from typing import Any, Dict
from .models import Post
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models.query import QuerySet
from django.http import Http404
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView

PER_PAGE = 9

class PostListView(ListView):
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'page_title': 'Blog - ',
        })

        return context


def created_by(request, author_pk):
    user = User.objects.filter(pk=author_pk).first()

    if user is None:
        raise Http404()

    posts = Post.objects.get_published()\
        .filter(created_by__pk=author_pk)
    user_full_name = user.username

    if user.first_name:
        user_full_name = f'{user.first_name} {user.last_name}'
    
    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    page_title = 'Posts of ' + user_full_name + ' - '

    return render(
        request,
        'blog/home.html',
        {
            'page_title': page_title,
            'page_obj': page_obj,
        }
    )


class CreatedByListView(PostListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_context: dict[str, Any] = {}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username

        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'
        page_title = 'Posts of ' + user_full_name + ' - '

        ctx.update({
            'page_title': page_title,
        })

        return ctx

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context['user'].pk)
        return qs

    def get(self, request, *args, **kwargs):
        author_pk = self.kwargs.get('author_pk')
        user = User.objects.filter(pk=author_pk).first()

        if user is None:
            raise Http404()

        self._temp_context.update({
            'author_pk': author_pk,
            'user': user,
        })

        return super().get(request, *args, **kwargs)


class CategoryListView(PostListView):
    allow_empty = False

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            category__slug=self.kwargs.get('slug')
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page_title = (
            f'{self.object_list[0].category.name} Category - ')
        ctx.update({
            'page_title': page_title,
        })
        return ctx


class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            tags__slug=self.kwargs.get('slug')
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page_title = self.kwargs.get('slug') + ' Tag - '

        ctx.update({
            'page_title': page_title,
        })
        return ctx


class SearchListView(PostListView):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._search_value = ''

    def setup(self, request, *args, **kwargs):
        self._search_value = request.GET.get('search', '').strip()
        return super().setup(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Any]:
        search_value = self._search_value
        return super().get_queryset().filter(
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)
        )[:PER_PAGE]

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        search_value = self._search_value
        ctx.update({
            'page_title': f'{search_value[:30]} Search - ',
            'search_value': search_value,
        })
        return ctx

    def get(self, request, *args, **kwargs):
        if self._search_value == '':
            return redirect('blog:home')
        return super().get(request, *args, **kwargs)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post.html'
    slug_field = 'slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        post = self.get_object()
        page_title = f'{post.title} Post - ' 
        ctx.update({
            'page_title': page_title,
        })
        return ctx

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(is_published=True)

src/blog/templates/blog/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<main class="main-content main-background section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">
      {% if posts %}
      <div class="card-grid">
        {% for post in posts %}
        <article class="card">

          {% if post.cover %}
          <div class="card-cover-wrapper">
            <a href="{{ post.get_absolute_url }}" class="card-cover-link">
              <img class="card-cover" loading="lazy" src="{{ post.cover.url }}" alt="Cover post {{ post.title }}">
            </a>
          </div>
          {% endif %}

          <div class="card-text-wrapper">
            <div class="card-title-wrapper">
              <a href="{{ post.get_absolute_url }}" class="card-title-link">
                <h2 class="card-title">{{ post.title }}</h2>
              </a>
            </div>

            <div class="card-content-wrapper">
              <p class="card-content">
                {{ post.excerpt }}
              </p>

              <div class="card-actions">
                <a class="card-action-link" href="{{ post.get_absolute_url }}">
                  <span>Read</span>
                  <i class="fa-solid fa-circle-arrow-right"></i>
                </a>
              </div>
            </div>
          </div>

        </article>
        {% endfor %}
      </div>
      {% else %}
        {% include "partials/nothing.html" with extra="News are empty!" %}
      {% endif %}
    </div>
  </div>
</main>

{% endblock content %}

src/blog/templates/blog/post.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- Main content -->
<main class="single-post-content section-content-narrow">
  <div class="single-post-gap section-gap">

    {% if post.cover and post.cover_in_post_content %}
    <div class="single-post-cover pb-base">
      <img loading="lazy" src="{{ post.cover.url }}" alt="{{ post.title }} Cover">
    </div>
    {% endif %}

    <h2 class="single-post-title pb-base center">
      {{ post.title }}
    </h2>

    <div class="post-meta pb-base">
      <div class="post-meta-item">
        <a class="post-meta-link" href="{% url 'blog:created_by' post.created_by.pk  %}">
          <i class="fa-solid fa-user"></i>
          <span>
            {% if post.created_by.first_name %}
            {{ post.created_by.first_name }}
            {{ post.created_by.last_name }}
            {% else %}
            {{ post.created_by.username }}
            {% endif %}
          </span>
        </a>
      </div>
      <div class="post-meta-item">
        <span class="post-meta-link">
          <i class="fa-solid fa-calendar-days"></i>
          <span>
            {{ post.created_at | date:'d/m/Y' }}
          </span>
        </span>
      </div>

      {% if post.category %}
      <div class="post-meta-item">
        <a class="post-meta-link" href="{% url 'blog:category' post.category.slug  %}">
          <i class="fa-solid fa-tag"></i>
          <span>
            {{ post.category.name }}
          </span>
        </a>
      </div>
      {% endif %}

    </div>

    <p class="single-post-excerpt pb-base">
      {{ post.excerpt | safe }}
    </p>

    <div class="separator"></div>

    <div class="single-post-content">

      {{ post.content | safe }}

      {% if post.tags.exists %}
      <div class="post-tags">
        <span>Tags: </span>

        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag' tag.slug %}">
          <i class="fa-solid fa-link"></i>
          <span>{{ tag.name }}</span>
        </a>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</main>

{% endblock content %}